require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/bitmovin/cocoapod-specs.git'

platform :ios, '12.0'
install! 'cocoapods', :deterministic_uuids => false

target 'BasicPlayer' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
  )

  target 'BasicPlayerTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
