#import "React/RCTViewManager.h"

/**
 * Bitmovin Video Manager
 *
 * This is the actual interface for react natve to use when calling from js to native code. It decribes the module and properties,
 * events etc.
 */
@interface RCT_EXTERN_MODULE(RNTBitmovinVideoManager, RCTViewManager)

/**
 * Source
 *
 * The source property used to instantiate the bitmovin player. It has information like stream, title etc.
 */
RCT_EXPORT_VIEW_PROPERTY(source, NSDictionary)

/**
 * Config
 *
 * The player configration object that conaints license key etc
 */
RCT_EXPORT_VIEW_PROPERTY(config, NSDictionary)

/**
 * Events goes here
 */
RCT_EXPORT_VIEW_PROPERTY(onReady, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onPlay, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onPlaying, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onPaused, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onSeek, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onSeeked, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onTimeShift, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onTimeShifted, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onVolumeChanged, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onMuted, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onUnmuted, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onPlayerResized, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onPlaybackFinished, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onError, RCTDirectEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onWarning, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onStallStarted, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onStallEnded, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onAudioChanged, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onAudioAdded, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onAudioRemoved, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onVideoQualityChanged, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onAudioQualityChanged, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onVideoDownloadQualityChange, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onAudioDownloadQualityChange, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onVideoDownloadQualityChanged, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onAudioDownloadQualityChanged, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onVideoPlaybackQualityChanged, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onAudioPlaybackQualityChanged, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onTimeChanged, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onSegmentPlayback, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onMetadata, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onMetadataParsed, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onMetadataChanged, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onVideoAdaptation, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onAudioAdaptation, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onDownloadFinished, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onSegmentRequestFinished, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onCastAvailable, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onCastStopped, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onCastStart, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onCastStarted, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onCastWaitingForDevice, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onSourceLoaded, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onSourceUnloaded, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onAirplayAvailable, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onAirplayChanged, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onDestroy, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onPlaybackSpeedChanged, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onDurationChanged, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onViewModeChanged, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onModuleReady, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onSubtitleEnable, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onSubtitleEnabled, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onSubtitleDisable, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onSubtitleDisabled, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onVideoQualityAdded, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onVideoQualityRemoved, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onAudioQualityAdded, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onAudioQualityRemoved, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onTargetLatencyChanged, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onLatencyModeChanged, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onLicenseValidated, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onDrmLicenseAdded, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onAspectRatioChanged, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onPictureInPictureAvailabilityChanged, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onPictureInPictureEnter, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onPictureInPictureExit, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onControlsHide, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onControlsShow, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onSourceError, RCTBubblingEventBlock)

@end
