name: QA

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install dependencies
        run: |
          yarn install --immutable
          cd examples/BasicPlayer && yarn install --immutable
          cd ../BasicPlayerTV && yarn install --immutable
          cd ../BasicPlayerWeb && yarn install --immutable
      - name: Typecheck
        uses: EPMatt/reviewdog-action-tsc@v1
      - uses: gozala/typescript-error-reporter-action@v1.0.8
